### ISSUE TITLE
[Change Request]: Add search/filter functionality to the Select component

### ISSUE THREAD

**Issue by chromaticWaster** [capitec/omni-components#122]
### What type of enhancement/feature is this?

Visual Changes to existing UI Components, Behaviour Changes to existing UI Components

### Description

- Add search functionality on the Select component.
- Limit the amount of selectable items in the Select component 

**Questions**
Should the Select component provide this functionality?

### Use Case/Reasoning for enhancement/feature.

Allow users to search for a specific item in the Select component.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have [searched for existing issues](https://github.com/capitec/omni-components/issues) and to the best of my knowledge this is not a duplicate
- [X] This is a single enhancement/feature

**Comment by stefan505** [comment]
> Questions
Should the Select component provide this functionality?

I think so yes. Handy feature to have, with sensible default behaviour, but it would be highly advantageous if the search logic can be overridden from the consumer-side.
