### ISSUE TITLE
[Bug]: Add blur on enter functionality to text field component

### ISSUE THREAD

**Issue by chromaticWaster** [capitec/omni-components#179]
### Components Version

0.8.1

### Which package type are you using?

Unbundled

### What type of bug is this?

Behaviour Error

### Description

This issue was picked up by a consumer of the Text field component. the blur on enter functionality is not available on this input component.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have [searched for existing issues](https://github.com/capitec/omni-components/issues) and to the best of my knowledge this is not a duplicate

**Comment by Gathin23** [comment]
Could you elaborate on how I could solve the issue and would like to be assigned
