### ISSUE TITLE
[Bug]: Button component slotted content has unwanted margins applied

### ISSUE THREAD

**Issue by chromaticWaster** [capitec/omni-components#45]
### Components Version

latest

### Which package type are you using?

Unbundled

### What type of bug is this?

Rendering Error

### Test Case/Reproduction

https://capitec.github.io/open-source/?repo=Omni-Components&path=%3Fpath%3D%2Fdocs%2Fui-components-button--slot

### Description

The Button component slotted content has margin applied based on the value provided to the  slotPosition property this results in unwanted margins applied to the slotted content that causes a undesired render result on the Button.

slotPosition = top

![image](https://user-images.githubusercontent.com/22874454/198221192-b8cf7f30-65b8-4e58-99d4-49ea656f33da.png)

slotPosition = bottom

![image](https://user-images.githubusercontent.com/22874454/198221262-2db90a34-0ce5-4d6e-ada1-81c914a032f5.png)

slotPosition = right

![image](https://user-images.githubusercontent.com/22874454/198221382-c433f0a5-503b-423a-b41d-18db976faad6.png)

slotPosition = left

![image](https://user-images.githubusercontent.com/22874454/198221332-0f728d31-836e-461d-8726-65db604c53bc.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have [searched for existing issues](https://github.com/capitec/omni-components/issues) and to the best of my knowledge this is not a duplicate

**Comment by BOTLANNER** [comment]
Is this not expected behaviour when a slot-position is specified?

When omitting any slot-position attribute, the icon renders in the middle as expected:
![image](https://user-images.githubusercontent.com/16349308/199171653-42c46bc6-c70a-4f67-b552-4fa407895efe.png)

**Comment by stefan505** [comment]
The actual issue is the expected behaviour associated with the `slot-position` attribute. Its intention is to reposition slotted content relative to the `label` prop. If a label is not specified, `slot-position` should be omitted. Documentation of the prop to be updated to better reflect this.

**Comment by BOTLANNER** [comment]
The slot position has a default of 'left' which can still cause this to occur when omitted. A potential fix would be to update the default slot position to be empty instead.
