### ISSUE TITLE
[Bug]: Button CSS Property Alignment

### ISSUE THREAD

**Issue by jn42lm1** [capitec/omni-components#65]
### Components Version

0.0.3

### Which package type are you using?

Unbundled

### What type of bug is this?

Behaviour Error

### Description

The Button component is currently does not expose CSS properties in the same way for all types. The individual types result in inaccessible behaviours that should instead be smart defaults that can be change from the outside with CSS properties.

1. Clear & White - exposes `hover-background-color`, while Primary & Secondary does not
2. Box shadows are hard coded in Primary, Secondary, and Clear. Should be a CSS var available to all 4.
3. Clear & White - exposes additional `active-border-color` & `active-border-width` which Primary & Secondary does not.
4. Line 260 -> background-color: unset; is applied to clear button types on mobile devices, which removes the background completely when the button is pressed, which the user has no control over, should removed or changed to a value the user has control over e.g. `var(--omni-button-clear-background-color, transparent);`
5. Expose background css properties as `background` instead of `background-color`, as this will allow for other types of backgrounds to be provided, like images and gradients.

In general, all button types should implement their own smart defaults, but still expose all the same properties so that the user can override them form the outside.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have [searched for existing issues](https://github.com/capitec/omni-components/issues) and to the best of my knowledge this is not a duplicate

**Comment by stefan505** [comment]
@BOTLANNER  and @chromaticWaster I think we should expose a `background` var for every equivalent `background-color` var. This does mean that background could be set for default, hover and active states for each permutation. Thoughts?
