### ISSUE TITLE
[Change Request]: Component story improvements

### ISSUE THREAD

**Issue by stefan505** [capitec/omni-components#71]
### What type of enhancement/feature is this?

Documentation Improvements

### Description

Consider the following improvements:

1. Improve Code Editor background styling.
2. Add Story descriptions. (extend the CSF 3 spec)
3. Ensure Stories are dark mode friendly.

### Use Case/Reasoning for enhancement/feature.

Usability enhancements for component Stories.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have [searched for existing issues](https://github.com/capitec/omni-components/issues) and to the best of my knowledge this is not a duplicate
- [X] This is a single enhancement/feature

**Comment by chromaticWaster** [comment]
Ensure that the contribution guide is updated accordingly.
